global:
  pdf_switch: 0
  pdf_password: None
comics:
- name: 海贼王
  path: haizeiwang
  last_chapter: 84
  download_limit: 5
  last_check_time: '2026-02-26 03:59:45'
- name: 电锯人
  path: dianjuren
  last_chapter: 84
  download_limit: 5
  last_check_time: '2026-02-26 03:59:57'
